#!/bin/sh
#
# site-condense.sh: generate the project pages for the project site.
#
# Convention: the homelab project's documents/09-project-pages-conventions.md
# (standard page set). Generates site.out/todo.html, site.out/prompts.html,
# site.out/documents.html, and site.out/records.html from THIS project's own
# TODO.md, prompts/, documents/, and records/ at build time, so the pages
# stay current without hand-editing.
#
#   todo.html       - open items (completed items summarized as a count).
#                     Handles both `* [ ]` and `- [ ]` bullet styles.
#   prompts.html    - index of prompts/ (the ENTIRE tree, grouped by
#                     directory), with links to full-text pages.
#   documents.html  - index of documents/, with links to full-text pages.
#   records.html    - index of records/, with links to full-text pages.
#
# Every .md file under prompts/ (whole tree), documents/, and records/ is
# also published as its own full-text page, e.g. site.out/prompts-common-
# 02-universal-rules.html. Markdown is converted with pandoc when available;
# otherwise a minimal renderer is used, so the build stays portable.
#
# Reuses site.in/template.html (marker <!-- SITE-CONTENT -->, __TITLE__).
#
# Usage: site-condense.sh
set -eu

DIRECTORY_SCRIPT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$DIRECTORY_SCRIPT/.." && pwd)
DIRECTORY_INPUT="$REPOSITORY_ROOT/site.in"
DIRECTORY_OUTPUT="$REPOSITORY_ROOT/site.out"
FILE_TEMPLATE="$DIRECTORY_INPUT/template.html"
COMMENT_MARKER='<!-- SITE-CONTENT -->'

mkdir -p "$DIRECTORY_OUTPUT"

# html_escape: escape & < > for safe inclusion in HTML text.
html_escape() {
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'
}

# page: wrap the given content file in the site template.
# Usage: page TITLE CONTENT_FILE OUTPUT_FILE
page() {
    title=$1
    content=$2
    output=$3
    title_escaped=$(printf '%s' "$title" | sed 's/\\/\\\\/g; s/&/\\&/g; s|/|\\/|g')
    {
        echo '<!-- generated by scripts/site-condense.sh; do not edit manually -->'
        sed "s/__TITLE__/$title_escaped/g" "$FILE_TEMPLATE" | sed "/$COMMENT_MARKER/q" | sed '$d'
        sed 's/^/    /' "$content"
        sed -n "/$COMMENT_MARKER/,\$p" "$FILE_TEMPLATE" | sed '1d'
    } > "$output"
}

# inline: render inline markdown (code spans, bold, links) as HTML.
# Input is already HTML-escaped.
inline() {
    text=$1
    text=$(printf '%s' "$text" | sed 's/`\([^`]*\)`/<code>\1<\/code>/g')
    text=$(printf '%s' "$text" | sed 's/\*\*\([^*]*\)\*\*/<strong>\1<\/strong>/g')
    text=$(printf '%s' "$text" | sed 's/\[\([^]]*\)\](\([^)]*\))/<a href="\2">\1<\/a>/g')
    printf '%s' "$text"
}

# minimal_md_to_html: fallback markdown -> HTML fragment (used when pandoc
# is unavailable). Handles ATX headings, fenced code blocks, bullet and
# ordered lists, and paragraphs; inline markup via the inline helper.
minimal_md_to_html() {
    file=$1
    in_code=0
    in_list=0
    list_kind=""
    while IFS= read -r line; do
        case "$line" in
            '```'*)
                if [ "$in_code" -eq 0 ]; then
                    printf '<pre><code>\n'
                    in_code=1
                else
                    printf '</code></pre>\n'
                    in_code=0
                fi
                ;;
            '#'*)
                [ "$in_list" -eq 1 ] && { printf '</%s>\n' "$list_kind"; in_list=0; }
                case "$line" in
                    '###### '*) h=6 ;;
                    '##### '*)  h=5 ;;
                    '#### '*)   h=4 ;;
                    '### '*)    h=3 ;;
                    '## '*)     h=2 ;;
                    '# '*)      h=1 ;;
                    *)          h=0 ;;
                esac
                if [ "$h" -gt 0 ]; then
                    text=$(printf '%s' "$line" | sed "s/^#\{$h\}[[:space:]]*//")
                    printf '<h%d>%s</h%d>\n' "$h" "$(inline "$(printf '%s' "$text" | html_escape)")" "$h"
                else
                    printf '%s\n' "$(printf '%s' "$line" | html_escape)"
                fi
                ;;
            '- '*|'* '*|'+ '*)
                if [ "$in_list" -eq 0 ]; then
                    printf '<ul>\n'
                    in_list=1
                    list_kind=ul
                fi
                item=${line#??}
                printf '  <li>%s</li>\n' "$(inline "$(printf '%s' "$item" | html_escape)")"
                ;;
            [0-9]*'. '*)
                if [ "$in_list" -eq 0 ]; then
                    printf '<ol>\n'
                    in_list=1
                    list_kind=ol
                fi
                item=${line#*.}
                item=${item# }
                printf '  <li>%s</li>\n' "$(inline "$(printf '%s' "$item" | html_escape)")"
                ;;
            '')
                [ "$in_list" -eq 1 ] && { printf '</%s>\n' "$list_kind"; in_list=0; }
                [ "$in_code" -eq 0 ] && printf '\n'
                ;;
            *)
                [ "$in_list" -eq 1 ] && { printf '</%s>\n' "$list_kind"; in_list=0; }
                if [ "$in_code" -eq 0 ]; then
                    printf '<p>%s</p>\n' "$(inline "$(printf '%s' "$line" | html_escape)")"
                else
                    printf '%s\n' "$(printf '%s' "$line" | html_escape)"
                fi
                ;;
        esac
    done < "$file"
    if [ "$in_list" -eq 1 ]; then
        printf '</%s>\n' "$list_kind"
    fi
    return 0
}

# find_pandoc: locate pandoc (on PATH, or in $HOME/bin) or print nothing.
find_pandoc() {
    if command -v pandoc >/dev/null 2>&1; then
        command -v pandoc
    elif [ -x "$HOME/bin/pandoc" ]; then
        printf '%s\n' "$HOME/bin/pandoc"
    fi
}

# md_to_html: markdown file -> HTML fragment. Prefers pandoc; falls back to
# the minimal renderer so the build works without extra tools.
md_to_html() {
    file=$1
    pandoc_bin=$(find_pandoc)
    if [ -n "$pandoc_bin" ]; then
        if "$pandoc_bin" -f markdown -t html --wrap=none "$file" 2>/dev/null; then
            return 0
        fi
    fi
    minimal_md_to_html "$file"
}

# first_heading: print the file's first heading (title), or empty.
first_heading() {
    sed -n 's/^#\{1,\}[[:space:]]*//p' "$1" | head -1
}

# flat_name: turn a repo-relative path into a flat output basename,
# e.g. prompts/common/02-universal-rules.md -> prompts-common-02-universal-rules
flat_name() {
    printf '%s' "$1" | sed 's/\.md$//; s|/|-|g'
}

# publish_tree: publish every .md file under DIR as a full-text page.
# Usage: publish_tree DIR
publish_tree() {
    dir=$1
    [ -d "$dir" ] || return 0
    for file in $(find "$dir" -name '*.md' -type f | sort); do
        rel=${file#"$REPOSITORY_ROOT"/}
        base=$(flat_name "$rel")
        heading=$(first_heading "$file")
        [ -n "$heading" ] || heading=$(basename "$rel")
        tmp_page=$(mktemp)
        md_to_html "$file" > "$tmp_page"
        page "$heading" "$tmp_page" "$DIRECTORY_OUTPUT/$base.html"
        rm -f "$tmp_page"
    done
}

# map_tree: emit an index page (title) listing DIR's files grouped by
# directory, each with a one-line purpose and a link to its full-text page.
# Usage: map_tree TITLE DIR OUTPUT_FILE
map_tree() {
    title=$1
    dir=$2
    output=$3
    tmp_index=$(mktemp)
    {
        echo "<h1>$title</h1>"
        if [ -d "$dir" ]; then
            prev_dir=""
            for file in $(find "$dir" -name '*.md' -type f | sort); do
                rel=${file#"$REPOSITORY_ROOT"/}
                dir_of=${rel%/*}
                base=$(flat_name "$rel")
                heading=$(first_heading "$file")
                [ -n "$heading" ] || heading='(no heading)'
                if [ "$dir_of" != "$prev_dir" ]; then
                    [ -n "$prev_dir" ] && echo '</ul>'
                    printf '<h3><code>%s/</code></h3>\n' "$(printf '%s' "$dir_of" | html_escape)"
                    echo '<ul>'
                    prev_dir=$dir_of
                fi
                printf '  <li><code>%s</code> — %s — <a href="%s.html">read</a></li>\n' \
                    "$(printf '%s' "$rel" | html_escape)" \
                    "$(printf '%s' "$heading" | html_escape)" \
                    "$base"
            done
            [ -n "$prev_dir" ] && echo '</ul>'
        else
            echo '<p>no directory</p>'
        fi
    } > "$tmp_index"
    page "$title" "$tmp_index" "$output"
    rm -f "$tmp_index"
}

FILE_TODO="$REPOSITORY_ROOT/TODO.md"

# --- todo.html ---------------------------------------------------------------
# Nested items stay nested. The renderer tracks indentation as a stack of
# widths: a deeper item opens a sub-list, a shallower one closes it, and a
# line at the left margin ends the lists. An indented line that is not an
# item is continuation text and belongs to the item above it. Completed items
# are counted, not listed.
tmp_todo=$(mktemp)
tmp_items=$(mktemp)
if [ -f "$FILE_TODO" ]; then
    open_count=$(grep -cE '^[[:space:]]*[*\-] \[ \]' "$FILE_TODO" || true)
    done_count=$(grep -cE '^[[:space:]]*[*\-] \[[xX]\]' "$FILE_TODO" || true)
else
    open_count=0
    done_count=0
fi

if [ -f "$FILE_TODO" ]; then
    awk '
        function escape_html(text) {
            gsub(/&/, "\\&amp;", text)
            gsub(/</, "\\&lt;", text)
            gsub(/>/, "\\&gt;", text)
            return text
        }
        function item_body(text) {
            body = text
            sub(/^[[:space:]]*[*\-] \[ \][[:space:]]*/, "", body)
            return escape_html(body)
        }
        function list_close() {
            while (depth > 0) {
                print "</li>"
                print "</ul>"
                depth--
            }
        }
        /^[[:space:]]*[*\-] \[ \]/ {
            match($0, /^[[:space:]]*/)
            indent = RLENGTH
            if (0 == depth) {
                print "<ul>"
                depth = 1
                stack[1] = indent
                printf "<li>%s", item_body($0)
            } else if (indent > stack[depth]) {
                print "<ul>"
                depth++
                stack[depth] = indent
                printf "<li>%s", item_body($0)
            } else {
                while (depth > 1 && indent < stack[depth]) {
                    print "</li>"
                    print "</ul>"
                    depth--
                }
                if (indent == stack[depth]) {
                    print "</li>"
                    printf "<li>%s", item_body($0)
                } else {
                    list_close()
                    print "<ul>"
                    depth = 1
                    stack[1] = indent
                    printf "<li>%s", item_body($0)
                }
            }
            next
        }
        depth > 0 && /^[[:space:]]+[^[:space:]]/ {
            continuation = $0
            sub(/^[[:space:]]+/, "", continuation)
            printf " %s", escape_html(continuation)
            next
        }
        depth > 0 && /[^[:space:]]/ {
            list_close()
        }
        END { list_close() }
    ' "$FILE_TODO" > "$tmp_items"
fi

{
    echo '<h1>Todo</h1>'
    echo "<p>Condensed from <code>TODO.md</code> at build time: $open_count open item(s), $done_count completed.</p>"
    if [ -s "$tmp_items" ]; then
        cat "$tmp_items"
    else
        echo '<p>No open items.</p>'
    fi
} > "$tmp_todo"
rm -f "$tmp_items"
page 'Todo' "$tmp_todo" "$DIRECTORY_OUTPUT/todo.html"
rm -f "$tmp_todo"

# --- prompts.html / documents.html / records.html + full-text pages ---------
map_tree 'Prompts' "$REPOSITORY_ROOT/prompts" "$DIRECTORY_OUTPUT/prompts.html"
publish_tree "$REPOSITORY_ROOT/prompts"
map_tree 'Documents' "$REPOSITORY_ROOT/documents" "$DIRECTORY_OUTPUT/documents.html"
publish_tree "$REPOSITORY_ROOT/documents"
map_tree 'Records' "$REPOSITORY_ROOT/records" "$DIRECTORY_OUTPUT/records.html"
publish_tree "$REPOSITORY_ROOT/records"

# --- phase.txt (machine-readable project phase for the homelab index) ------
# Reads PHASES.md ("Current: phase N — <description> — state") and writes
# site.out/phase.txt as KEY=VALUE lines (PHASE=N, PHASE_STATE=state). The state
# is the last dash-separated field and must be one of the three allowed values;
# a description in the middle is for people. A line that does not fit leaves
# phase.txt unwritten, and the homelab index simply shows the activity without
# a phase. The homelab fetch stages this file and the site merges it with the
# registry activity status.
FILE_PHASES="$REPOSITORY_ROOT/PHASES.md"
if [ -f "$FILE_PHASES" ]; then
    phase_line=$(grep -m1 '^Current: phase ' "$FILE_PHASES" || true)
    phase_num=$(printf '%s' "$phase_line" | sed -n 's/^Current: phase \([0-9][0-9]*\).*/\1/p')
    phase_state=$(printf '%s' "$phase_line" | awk -F'—' 'NF > 1 { state = $NF; gsub(/^[ \t]+|[ \t]+$/, "", state); print state }')
    case "$phase_state" in
        not-started | started | complete)
            ;;
        *)
            phase_state=""
            ;;
    esac
    if [ -n "$phase_num" ] && [ -n "$phase_state" ]; then
        {
            echo "PHASE=$phase_num"
            echo "PHASE_STATE=$phase_state"
        } > "$DIRECTORY_OUTPUT/phase.txt"
        echo "site-condense: wrote phase.txt (phase $phase_num, $phase_state)"
    else
        echo "site-condense: PHASES.md has no 'Current: phase N — state' line; phase.txt not written" >&2
    fi
fi

# --- pages.txt (the page set for the homelab-injected navigation) ----------
# The homelab renders ONE navigation bar per project page (conventions
# section 12); site.in/pages.nav (optional) declares this project's page set,
# one "href|Label" per line, and must contain the standard page set. The
# homelab reads site.out/pages.txt and refuses a list that does not; without
# the file the standard set is published.
FILE_PAGES_NAV="$REPOSITORY_ROOT/site.in/pages.nav"
if [ -f "$FILE_PAGES_NAV" ]; then
    cp "$FILE_PAGES_NAV" "$DIRECTORY_OUTPUT/pages.txt"
else
    cat > "$DIRECTORY_OUTPUT/pages.txt" <<'HOMELAB_PAGES'
index.html|Summary
dashboard.html|Dashboard
todo.html|Todo
prompts.html|Prompts
documents.html|Documents
records.html|Records
HOMELAB_PAGES
fi
echo "site-condense: wrote pages.txt (project page set for the homelab nav)"

echo "site-condense: built todo.html, prompts.html, documents.html, records.html + full-text pages into $DIRECTORY_OUTPUT"
exit 0
