#!/bin/sh
#
# site-build.sh: generate the static site in site.out/ from site.in/.
#
# Feature: prompts/features/01-site-build.md
#
# Usage: site-build.sh [DIRECTORY_INPUT] [DIRECTORY_OUTPUT]
#
# The default DIRECTORY_INPUT is site.in/ and the default DIRECTORY_OUTPUT is
# site.out/, both relative to the repository root.
# Every site.in/*.txt input file is converted to site.out/<name>.html.
# The HTML page structure lives in site.in/template.html, not in this script.
# The template marker <!-- SITE-CONTENT --> marks where page content is inserted.
#
# A page may contain __KEY__ placeholders for live state. Values come from the
# state file (dataflow.out/site-state.txt by default, overridable with
# SITE_STATE_FILE), written by scripts/site-state-fetch.sh. When the state file
# is absent, remaining placeholders render as "unavailable", so the build stays
# portable.
#
# Generated output is stamped with a generated-file marker and must not be
# edited manually.
set -eu

DIRECTORY_SCRIPT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPOSITORY_ROOT=$(CDPATH= cd -- "$DIRECTORY_SCRIPT/.." && pwd)

DIRECTORY_INPUT=${1:-"$REPOSITORY_ROOT/site.in"}
DIRECTORY_OUTPUT=${2:-"$REPOSITORY_ROOT/site.out"}
FILE_TEMPLATE="$DIRECTORY_INPUT/template.html"
COMMENT_MARKER='<!-- SITE-CONTENT -->'
FILE_STATE=${SITE_STATE_FILE:-"$REPOSITORY_ROOT/dataflow.out/site-state.txt"}

if [ ! -d "$DIRECTORY_INPUT" ]; then
    echo "site-build: input directory not found: $DIRECTORY_INPUT" >&2
    exit 1
fi

if [ ! -f "$FILE_TEMPLATE" ]; then
    echo "site-build: template not found: $FILE_TEMPLATE" >&2
    exit 1
fi

if ! grep -q "$COMMENT_MARKER" "$FILE_TEMPLATE"; then
    echo "site-build: template is missing the marker line: $COMMENT_MARKER" >&2
    exit 1
fi

# Substitute __KEY__ placeholders from the state file; any leftover __KEY__
# renders as "unavailable", so a build without state stays portable.
substitute_state() {
    file_input=$1
    file_output=$2
    file_temporary=$(mktemp)

    cp "$file_input" "$file_temporary"

    if [ -f "$FILE_STATE" ]; then
        while IFS='=' read -r key value; do
            [ -n "$key" ] || continue
            value_escaped=$(printf '%s' "$value" | sed 's/[&\\|]/\\&/g')
            sed "s|__${key}__|${value_escaped}|g" "$file_temporary" > "$file_temporary.new"
            mv "$file_temporary.new" "$file_temporary"
        done < "$FILE_STATE"
    fi

    sed 's/__[A-Z0-9_]*__/unavailable/g' "$file_temporary" > "$file_output"
    rm -f "$file_temporary"
}

# Map a page basename to its display title: the index page is the
# project's title, everything else is the basename, title-cased.
page_title() {
    name_base=$1

    case "$name_base" in
        index) echo "Psyche1" ;;
        *)     echo "$name_base" | tr '_-' '  ' | awk '{for (i = 1; i <= NF; i++) $i = toupper(substr($i, 1, 1)) substr($i, 2); print}' ;;
    esac
}

# Start from an empty output tree: site.out/ is generated-only, so a renamed
# or removed page must not linger as a published orphan. Keep .gitkeep so the
# repository structure stays valid before the first build.
if [ -d "$DIRECTORY_OUTPUT" ]; then
    find "$DIRECTORY_OUTPUT" -mindepth 1 -maxdepth 1 ! -name '.gitkeep' -exec rm -rf {} +
fi
mkdir -p "$DIRECTORY_OUTPUT"

count_built=0
for file_input in "$DIRECTORY_INPUT"/*.txt; do
    if [ ! -f "$file_input" ]; then
        continue
    fi
    name_base=$(basename "$file_input" .txt)
    title_escaped=$(page_title "$name_base" | sed 's/\\/\\\\/g; s/&/\\&/g; s|/|\\/|g')
    file_output="$DIRECTORY_OUTPUT/$name_base.html"
    file_temporary=$(mktemp)
    {
        echo '<!-- generated by scripts/site-build.sh; do not edit manually -->'
        sed "s/__TITLE__/$title_escaped/g" "$FILE_TEMPLATE" | sed "/$COMMENT_MARKER/q" | sed '$d'
        sed 's/^/    /' "$file_input"
        sed -n "/$COMMENT_MARKER/,\$p" "$FILE_TEMPLATE" | sed '1d'
    } > "$file_temporary"
    substitute_state "$file_temporary" "$file_output"
    rm -f "$file_temporary"
    count_built=$((count_built + 1))
done

echo "site-build: built $count_built page(s) into $DIRECTORY_OUTPUT"

# Copy authored assets (non-.txt, non-template files such as scripts, styles,
# and images) verbatim, so a page can reference them by relative path.
# site.in/pages.nav is input for the page set, not a published asset.
count_assets=0
for file_asset in "$DIRECTORY_INPUT"/*; do
    if [ ! -f "$file_asset" ]; then
        continue
    fi
    name_asset=$(basename "$file_asset")
    case "$name_asset" in
        .*|*.txt|template.html|pages.nav)
            continue
            ;;
    esac
    cp "$file_asset" "$DIRECTORY_OUTPUT/$name_asset"
    count_assets=$((count_assets + 1))
done

echo "site-build: copied $count_assets asset(s) into $DIRECTORY_OUTPUT"
exit 0
